### ISSUE TITLE
Error on google search

### ISSUE THREAD

**Issue by autli** [renma/tdjsfgs#10]
Ich habe uns an Position 23 gefunden. Wenn ich _Our mission - good sound_ anklicke kommt nur eine Fehlermeldung, keine Website. S. Bild
![tdj bei google](https://user-images.githubusercontent.com/35627082/35221155-6a1d839c-ff79-11e7-9113-34dc140640db.JPG)

**Comment by autli** [comment]
Nachtrag: Unter Windows10 und Edge

**Comment by renma** [comment]
Bei Google ist noch die alte URL gespeichert: https://tangodjsforgoodsound.info/about
Wir brauchen jetzt eine neue URL: https://tangodjsforgoodsound.info/mission

Wir können ein "redirect" einrichten, dann funzt auch die alte URL wieder.
Sollten wir das tun?

**Comment by renma** [comment]
Accepted.

**Comment by renma** [comment]
Rewritten in tangodjsforgoodsound/urls.py:
>>> url(r"^about/$", RedirectView.as_view(url='/mission'))
