### ISSUE TITLE
Extended search and/or selection functions

### ISSUE THREAD

**Issue by renma** [renma/tdjsfgs#100]
To be able to handle several hundred DJ entries we need extended search and/or selection functions.

Possibilities
* Selector to show all DJS of a continent
* Selector to show all DJS of a country
* Search field (text)
* Other

**Comment by renma** [comment]
A single-word search box looks good, is very practical and should actually meet all the requirements.

Implementation with javascript.
Implemented in 1.5.7.

**Comment by renma** [comment]
Maybe we can introduce some kind of normalization.

...so that typing `rene` finds René.

**Comment by renma** [comment]
Basic normalisation, which should cover most cases, implemented.

javascript:
`str.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "");`

**Comment by renma** [comment]
Already seen?

**Comment by renma** [comment]
Seams to work:

<img width="1085" alt="djsearch" src="https://user-images.githubusercontent.com/35080009/104307156-2b848280-54cf-11eb-87c4-c982388d95cc.png">

**Comment by autli** [comment]
Now, notification works too.

**Comment by renma** [comment]
Installed on test-server.

**Comment by renma** [comment]
Some fixes:

- Hidden the unsightly scrolling of the page when resizing the table (only a quick fix).
- Restored row spacing in the table.
- Identical table headers for DJs and Technology.

**Comment by autli** [comment]
> Identical table headers for DJs and Technology.

Not quite yet. DJ (technology) vs Registered DJs (DJ Site) -> should be DJ.

**Comment by renma** [comment]
I meant the **style** of the header (font, background color, padding, ...).
:-)

> -> should be DJ.

"DJ" as a header is what I like.
"Registered DJs" as suggested in #122 I find I find inappropriate.

So finally header set to "DJ" on the DJ page.

**Comment by renma** [comment]
@autli 
Einverstanden mit der Implementierung?

**Comment by autli** [comment]
Ja, sehr gut gemacht!
