### ISSUE TITLE
Good sound more concrete

### ISSUE THREAD

**Issue by renma** [renma/tdjsfgs#103]
The DJ is only partly responsible for the good sound at a Milonga. For the other part the organiser is responsible (PA etc.)

This fact should be clearly mentioned on tangoodjsforgoodsound.info.

**Comment by autli** [comment]
How about this:
The three most important factors for good sound in a venue are:
- good loudspeakers and good PA equipment
- good room acoustics
- good quality transfers of the original recordings
For the first two points the responsibility belongs to the organizer.

**Comment by renma** [comment]
That would be a start. Thanks!
Does it come under milestone 1.5.5?

**Comment by autli** [comment]
I don't know where to place. Needs too much room, no? In Mission?

**Comment by autli** [comment]
_Maybe a change for a better reading:_
The most important factors for good sound in a venue are the following.
Organizers responsibility: good loudspeakers, good PA equipment and good room acoustics
DJs responsibility: good quality transfers of the original recordings and good quality audio tools

**Comment by renma** [comment]
"**_Maybe_**" is hard to implement. Tried with slightly modified formatting.

**Comment by autli** [comment]
I think, now with text version 4 we have a very good elaboration by 4 eyes and 2 brains!
(Sorry, I tried my best, my education is not in creating German or even English texts and I like a verification of my proposals. Therefore **Maybe**) If you don't like how it runs at the moment, then maybe we need a third contributor. Unfortunately I can't contribute to your work as programmer.

**Comment by renma** [comment]
The formatting is not yet the burner (ok for me).
The question of additional contributors would be better discussed (via email) among us.

**Comment by autli** [comment]
Small change:
"Good loudspeakers, good PA equipment and **a** good room acoustics."

For now I don't know better -> we could close.

**Comment by renma** [comment]
Text adjusted to "Good loudspeakers, good PA equipment and a good room acoustics."
