### ISSUE TITLE
Modified: Minimal Sound Requirement Statement

### ISSUE THREAD

**Issue by autli** [renma/tdjsfgs#105]
Register

By submitting your registration, you agree to our **minimal sound requirement statement**:
 - We use good quality transfers of the original recordings.
- We don't play lossy formats (e.g. mp3, aac, youtube-downloads ...).
- We use good quality audio tools and software: e.g. interfaces, external sound cards, external DACs, sound processors. We do not consider internal DACs of mobile computers to be good enough.

**Comment by renma** [comment]
Two occurrences changed:
* Register: tangodjsforgoodsound/templates/registration/register.html
* DJEdit: tangodjsforgoodsound/templates/djeditbase.html

**Comment by autli** [comment]
well done. Can I close the issue or do you? What's the procedure in such cases?

**Comment by renma** [comment]
Fixed in 1.5.5

**Comment by renma** [comment]
Maybe we should replace
_"We do not consider internal **DACs** of mobile computers to be good enough"_
with
_"We do not consider internal **sound cards** of mobile computers to be good enough"_

**Comment by autli** [comment]
Yes, your proposal is better, thanks. But "internal" also bold (?)

Better English maybe?: We consider **internal sound cards** of mobile computers as not good enough.

**Comment by renma** [comment]
Bold was only for the GitHub entry :-)
Last variant is implemented.
