### ISSUE TITLE
djedit: Notes on entering DJ data

### ISSUE THREAD

**Issue by autli** [renma/tdjsfgs#106]
• Please note that your data is not visible on the website as long as Number of Milongas is set to zero.
• Please name your tools precisely, so readers may find information about in internet

To ensure the quality of our website, we have to exclude DJs with insufficient entries in relation to our **minimum sound requirement statement** (see below on this page).

**Comment by renma** [comment]
Added with the following adjustment:
* Please name your tools precisely, so that readers can find information about them on the Internet.
