### ISSUE TITLE
Rename Field 'Audio Interface/DAC' in Equipment

### ISSUE THREAD

**Issue by autli** [renma/tdjsfgs#107]
External Audio Interface/DAC
or
Ext. Audio interface/DAC
or
Audio interface/DAC (ext.)

**Comment by renma** [comment]
The first variant is by far the best - but too long.

How about **External AI/DAC**?

**Comment by autli** [comment]
Then my preference is: **Ext. Audio interface/DAC**
(many readers would not understand the meaning of **AI**)

**Comment by renma** [comment]
Question: is it clear to the reader, that  the "Ext." includes **both** Audio interface and DAC?

**Comment by autli** [comment]
Hm, good question.
Other approach: An **audio interface** is always external because its a device. Only a DAC has to be external, no? It's written like that in the _Minimal Sound Requirements Statements_ - no?
How much letters do we have for the field name?
How about: **Audio interface/ext. DAC**

**Comment by renma** [comment]
There is no limit for the field name. It is more an optical matter.

I can add two variations tomorrow. Then we can decide.

**Comment by renma** [comment]
External is now explicit in the sound requirements.
Therefore we can omit the term here. No change.
