### ISSUE TITLE
djedit: Pop-up Menu for AI/DAC

### ISSUE THREAD

**Issue by autli** [renma/tdjsfgs#108]
For field ext. AI/DAC we implement a _pop-up menu_ with a choice of known quality devices with an option for 'Other'. Multiple entries allowed.

**Comment by renma** [comment]
I think a drop-down list would almost make more sense.
See: https://de.wikipedia.org/wiki/Dropdown-Liste

**Comment by autli** [comment]
Yes, Drop-down is better and what I meant (wrong description on my part).

**Comment by renma** [comment]
Actually, I don't see a reasonable way to implement this.
