### ISSUE TITLE
Password Reset fails (sometimes)

### ISSUE THREAD

**Issue by autli** [renma/tdjsfgs#111]
DJ Alberto PW reset:
- Email with link for reset always goes to SPAM folder
- moved out from SPAM, link is no more valid often, not every time
Adress wrong?
https://tangodjsforgoodsound.info/accounts/reset/NA/5le .......

PW reset leads to:
[https://tangodjsforgoodsound.info](url)

**Comment by autli** [comment]
**Edit:**
PW reset leads to:
Sorry for your inconvenience!
......

**Comment by renma** [comment]
The wrong link is actually a bug.

In the password reset form (password_reset_email.html) the name is coded only for two sites:

{{protocol}}://tangodjsforgoodsound.cumparsita.ch
{{protocol}}://tangodjsforgoodsound.info

The password reset fails when we are working on tdjsfgs.uber.space.
The developer should implement a generic way to detect the correct URL.

Thanks for reporting.

**Comment by renma** [comment]
Can you please fill out a separate issue for the SPAM behaviour of the password reset.

**Comment by renma** [comment]
Should be fixed in 1.5.3-u7-1108-1.
To be tested.
