### ISSUE TITLE
Password Reset goes to SPAM

### ISSUE THREAD

**Issue by autli** [renma/tdjsfgs#112]
Password reset email goes to SPAM (detected in Apple Mail 12.2)

**Comment by renma** [comment]
I cannot reproduce this. Tried several times.

The SPAM Score is: X-Rspamd-Score: -0.29
Emails in my SPAM folder have values of 5.10 or much higher.

**Comment by autli** [comment]
I can also no longer reproduce this. Maybe it was an issue of the Swisscom-server.
