### ISSUE TITLE
Test Github with Firefox

### ISSUE THREAD

**Issue by autli** [renma/tdjsfgs#113]
Preview and DnD works with Firefox.
Now a test for edit

Yes EDIT works!
Edit also works after labeling
It looks like I have to use Firefox in future
**_Edit also works after message from other users_**

**Comment by renma** [comment]
Hast du einen veralteten Safari oder was?

**Comment by autli** [comment]
Nicht so alt, gehört zu Mojave und funktioniert sonst sehr gut.
Wiso kannst du mit deinem aktuellen Safari den Text nicht editieren und nur den Titel?

**Comment by renma** [comment]
Preview  mit Chrome Version 83.0.4103.97 (Official Build) Arch Linux (64-bit) funzt bestens.
![0 300x300](https://user-images.githubusercontent.com/35080009/98451050-9669b400-2142-11eb-9d27-12f8c44fcc87.jpg)

**Comment by autli** [comment]
Wie schon geschrieben: Funzt auch mit Firefox
Chrome? noch mehr Google in unserer Welt?

**Comment by renma** [comment]
Edit des Textes geht schon.
Ist mir einfach bis jetzt nicht in den Sinn gekommen, das ich das benutzen möchte.

Es ist tatsächlich schade, dass Chrome ein Google Produkt ist. Leider kann  der Safari (trotz dem Einsatz derselben Rendering-Engine)  in keiner Art und Weise mit einem Chrome unter Linux mithalten was Speed und Effizienz angeht. Chrome unter macOS fand ich unbrauchbar.

Genug davon :-)
