### ISSUE TITLE
Register: Yellow Marks

### ISSUE THREAD

**Issue by autli** [renma/tdjsfgs#114]
If _big four orchestras_ is wrong and passwords are correct:
then mark yellow _big four orchestras_ and don't empty and mark passwords

**Comment by renma** [comment]
The programmer was of the opinion that it had to be **exactly like this** and that it made sense.

It can be changed this way:
<= RegisterForm :: `widget=forms.PasswordInput(render_value=False)`
=> RegisterForm :: `widget=forms.PasswordInput(render_value=True)`

**Comment by autli** [comment]
> The programmer was of the opinion that it had to be exactly like this and that it made sense.

Then we should leave it as it is. It's OK for me.

**Comment by renma** [comment]
I thought it is already changed on the test-server?
You can try it out :-)

**Comment by autli** [comment]
Oh, tested now, very well done, thanks.
