### ISSUE TITLE
djedit: Notes on entering Data for Resque Equipment

### ISSUE THREAD

**Issue by autli** [renma/tdjsfgs#116]
Some DJs enter imprecise information to _Rescue Equipment_, therefore more information is needed here.
Worst case of DJ Autli:
![Bildschirmfoto 2020-11-08 um 22 43 08](https://user-images.githubusercontent.com/35627082/98521498-ce244900-2273-11eb-90ba-2dfc4ba71072.png)

Proposed text, placed on the right side of fields
"These tools you will need if one or more of your main devices fail. So it is logical, that their names must not be identical to the main devices (unless you have second identical devices at hand)."

**Comment by renma** [comment]
Könntest du Mal
**Message-ID: <969AC2B2-CA02-486F-94E3-CD3E0261E1E1@cumparsita.ch>**
beantworten bevor du neue Requirements definierst ;-) ;-) ;-) Oder hast du die nicht bekommen?

**Comment by autli** [comment]
Wo, wie finde ich
Message-ID: 969AC2B2-CA02-486F-94E3-CD3E0261E1E1@cumparsita.ch ?

**Comment by renma** [comment]
Mit der Funktion Suchen in deinem Email Programm?
Bei mir Search: message-id:969AC2B2-CA02-486F-94E3-CD3E0261E1E1@cumparsita.ch

Ich meine die:
Subject: Re: tdjsfgs: Migration auf uberspace-7
Date: 9 November 2020 at 08:17

**Comment by autli** [comment]
Meine Suchen Funktion in Apple Mail bringt leider das gewünschte Resultat nicht (ausser die Mail von Github).

**Comment by renma** [comment]
From: Rene Maurer <*@cumparsita.ch>
Subject: Re: tdjsfgs: Migration auf uberspace-7
Date: 9 November 2020 at 08:17
To: Albi <*@bluewin.ch>

> Vielen Dank für deine ausführlichen Tests.
> 
> Also dann werde ich noch deine Tabelle mit den Testresultate einbauen und eine Version 1.5.4 machen und dann tangodjsforgoodsound.info auf den neuen Server umstellen._
> 
> Nach ein paar Tagen kann ich dann bei uberspace die Migration abschliessen, so dass auch das tdjsfgs Login direkt auf uberspace-7 geht.
> 
> Einverstanden ?
> 

Ich habe
- Version auf 1.5.4 gesetzt
- Release-Notes gemacht
- deine Teststabelle integriert
- und das Handbuch aktualisiert.

Wenn du einverstanden bist schalte ich um auf “maintenance” und stelle die Nameserver bei https://www.domaindiscount24.com auf uberspace-7 um (dass kann dann einige Stunden dauern bis das überall aktiv ist).

Einverstanden?

**Comment by autli** [comment]
**Reden wir aneinander vorbei?** Albi

Von: *@bluewin.ch
Betreff: Fwd: tdjsfgs: Migration auf uberspace-7 Datum: **9. November 2020 um 10:48**
An: *@cumparsita.ch
Hallo René
Wie du unten siehst habe ich heute um 08:25 geantwortet mit „**Einverstanden**“
Hast du eine ausführlichere Antwort erwartet?
Lieber Gruss, Albi
NB: ich habe jetzt meinen SPAM-Filter zurückgesetzt in der Hoffnung, dass er besser funktionieren wird.

Anfang der weitergeleiteten Nachricht:
Von: *@bluewin.ch
Betreff: Aw: tdjsfgs: Migration auf uberspace-7 Datum: **9. November 2020 um 08:25**
An: *@cumparsita.ch
**Einverstanden.**
Diese Mail ist jetzt auch in meinem SPAM gelandet. Da sRmmt doch etwas nicht bei mir im Apple Mail - ich muss dem nachgehen...
Schöne Tag, Albi

Am 09.11.2020 um 08:17 schrieb *@cumparsita.ch:
Vielen Dank für deine ausführlichen Tests.
Also dann werde ich noch deine Tabelle mit den Testresultate einbauen und eine Version 1.5.4 machen und dann tangodjsforgoodsound.info auf den neuen Server umstellen.
Nach ein paar Tagen kann ich dann bei uberspace die MigraRon abschliessen, so dass auch das tdjsfgs Login direkt auf uberspace-7 geht.
Einverstanden ?
Ich habe
- Version auf 1.5.4 gesetzt
- Release-Notes gemacht
- deine Teststabelle integriert
- und das Handbuch aktualisiert.
Wenn du einverstanden bist schalte ich um auf “maintenance” und stelle die Nameserver bei hbps://www.domaindiscount24.com auf uberspace-7 um (dass kann dann einige Stunden dauern bis das überall akRv ist).
Einverstanden?

**Comment by renma** [comment]
**Nein wir reden nicht aneinander vorbei.**
**Offenbar sehe ich deine Emails nicht mehr.**

Die letzte Email die ich von dir (nicht via **github** sondern **direkt**) bekommen habe ist ist diese:
From: *@bluewin.ch
Subject: tdjsfgs: Testtabelle V. 1.5.3-u7-1108-1
Date: 8 November 2020 at 12:32
To: Maurer René <*@cumparsita.ch>

Ausser von dir kommen hier aber viele Mails an (sobald ich Zeit habe kann ich noch direkt im IMAP Server bei mir schauen, ob ich etwas finde).

NB1: Bis am 4.11. war dein Absender: Aubi <s*@bluewin.ch>; ab dem 5.11. nur noch : s*@bluewin.ch

NB2: SPAM wird von bluewin.ch bewertet nicht von MACMail (du hast mir Mal gesagt, dass du keinen SPAM Filter hast).

NB3: Am Schluss löschen wir aber diesen Issue :)

**Comment by autli** [comment]
Zu NB1: Swisscom erlaubt ab Dez. 20 keine Alias-Adressen mehr, darum ist 'Aubi' weg
Ich habe noch einmal nachgeschaut: Meine oben erwähnten Mails liegen im Postfach gesendet. (?)
Willst du auch den ursprünglichen Inhalt von diesem Issue gelöscht haben?

**Comment by renma** [comment]
Könntest du denn zum Schluss den ursprünglichen Inhalt in einem neuen Issue unterbringen?

**Comment by autli** [comment]
... ist gemacht. Ich schliesse - könnte man auch löschen?

**Comment by autli** [comment]
Ich fürchte ich kann nicht löschen weil ich nicht die Berechtigung dazu habe? Finde diesen Button nicht.
![Bildschirmfoto 2020-11-09 um 14 24 32](https://user-images.githubusercontent.com/35627082/98547177-1190ae80-2298-11eb-9bce-8038199c3241.png)
