### ISSUE TITLE
djedit: Notes on entering Data

### ISSUE THREAD

**Issue by autli** [renma/tdjsfgs#117]
Some DJs enter imprecise information to Rescue Equipment, therefore more information is needed here.
Worst case of DJ Autli:
![98521498-ce244900-2273-11eb-90ba-2dfc4ba71072](https://user-images.githubusercontent.com/35627082/98538020-7218ef00-228a-11eb-887f-d7400922fa75.png)
Proposed text, placed on the right side of fields
"These tools you will need if one or more of your main devices fail. So it is logical, that their names must not be identical to the main devices (unless you have second identical devices at hand)."

**Comment by renma** [comment]
Good idea, I do not like the proposed implementation so much. The site will be too crowded at some point, if we want to do the same for other sections.

Maybe we should place an info-icon (see https://de.wikipedia.org/wiki/Datei:Infobox_info_icon.svg) on the right of the title (Rescue Equipment, Musica, ...) that can be clicked. Clicking on it will bring a popup window to the foreground with the corresponding info.
 
* To the developers: means JavaScript and effort.
* To the designers: how should such a popup look like?

Note: an info-icon for each entry would be a bit exaggerated.

**Comment by autli** [comment]
> Maybe we should place an info-icon

Very good idea!

> Note: an info-icon for each entry would be a bit exaggerated.

I agree

**Comment by renma** [comment]
Implemented:

* info-box-account-data
The email address you enter here will be used for login and password Reset (it can be an advantage if this address does not match the one displayed on the website).

*  info-box-personal
Your personal data that you want to publish. The email address (optional) you enter here will be published on the website. We protect the address against SPAM with some simple tricks.

* info-box-musica
  Here you can say something about your sources, your preferences and your style.

* info-box-equipment
These are probably the most important data for the site. A valuable support for new DJs getting their first gear and an inspiration for advanced DJs looking for better and proven tools.

* info-box-rescue-equipment
These tools you will need if one or more of your main devices fail. So it is logical, that their names must not be identical to the main devices (unless you have second identical devices at hand).

Example:

![popup](https://user-images.githubusercontent.com/35080009/99995003-18e8a980-2dba-11eb-8f2a-cf97f18dc4b0.png)

Info Icon 24x24:

![info-icon_24x24](https://user-images.githubusercontent.com/35080009/99995103-3b7ac280-2dba-11eb-9fd4-89d047fd8a87.png)

**Comment by autli** [comment]
This sounds and looks very good and brings some colour as well. How about leading the eyes to the Info Icon by coloring them red or orange?

**Comment by renma** [comment]
> How about leading the eyes to the Info Icon by coloring them red or orange?

Do it after all.

**Comment by autli** [comment]
Looks good.
But while testing: Opening **Info** and scrolling after can create a mess. And in few cases the window can no longer be closed (needs reloading site).
If possible:
- Info should open close to the related icon (even better if the window could follow the icon while scrolling)
- only 1 **Info** window should be open at a time

![Bildschirmfoto 2020-11-25 um 11 32 32](https://user-images.githubusercontent.com/35627082/100217270-907e1c00-2f13-11eb-8ae3-1d017ac2a832.png)

**Comment by renma** [comment]
Sorry the Musica-Info-Box could not be closed with the "x" (I **forgot** to upload the fix).

Having only one box open is a good idea and  possible and made.

The rest gives too much to do compared to the profit.

**Comment by autli** [comment]
Implement a **Title Line** (bold) to the info window, so after scrolling it stays clear which categorie belongs to the text.
"Acconnt data, Personal, Musica, Equipment, Rescue equipment"

**Comment by renma** [comment]
Not a variant that knocks you out ;-)
It works.

**Comment by renma** [comment]
> How about leading the eyes to the Info Icon by coloring them red or orange?
>> Do it after all.

Is there anything coming?

**Comment by autli** [comment]
> Is there anything coming?

Nothing else, thanks.

**Comment by renma** [comment]
>>>> How about leading the eyes to the Info Icon by coloring them red or orange?

>>> Do it after all.

>> Is there anything coming?

> Nothing else, thanks.

So you do not provide red and/or orange colored info icons?

**Comment by autli** [comment]
> So you do not provide red and/or orange colored info icons?

No, I changed my mind, there is no need for this.

**Comment by renma** [comment]
Green (see above) or grey (see below)?

![screenshot](https://user-images.githubusercontent.com/35080009/100377826-53e51a00-3012-11eb-89b7-6de29fa00758.png)

**Comment by autli** [comment]
> This sounds and looks very good and brings some colour as well.

Green - of course!

**Comment by renma** [comment]
Green implemented!

**Comment by autli** [comment]
Green came back - orange is complementary ... for me ;-)
Sorry: If it's not too late -> the decision is yours. (I can live with black)

![Information_icon4_orange svg-30x30](https://user-images.githubusercontent.com/35627082/100388508-193bab80-302b-11eb-962d-1f939ed4bd08.png)

[https://commons.wikimedia.org/wiki/File:Information_icon4_orange.svg](url)

**Comment by renma** [comment]
Orange info-icon implemented.
