### ISSUE TITLE
Autocomplete for text fields not recommended

### ISSUE THREAD

**Issue by autli** [renma/tdjsfgs#12]

**Comment by renma** [comment]
Betrifft die folgenden Felder:
[
  "name",
  "province",
  "email",
  "useremail",
  "website",
  "sources",
  "favorites",
  "computermodel",
  "player",
  "audiointerface",
  "soundprocessor",
  "other_equipment",
  "backup_computermodel",
  "backup_player",
  "backup_audiointerface",
  "backup_soundprocessor",
  "backup_other_equipment"
]
Korrekt?

**Comment by autli** [comment]
Korrekt. Heute auf Mac/Safari ist autocomplete nicht mehr aktiv

**Comment by renma** [comment]
Serverseitig hat da nichts geändert!!!

**Comment by autli** [comment]
Gestern auf W10/Edge war autocomplete (AC), heute auf Mac/Safari&Firefox kein AC.
Verstehe ich nicht, liegt das am Edge?

**Comment by renma** [comment]
Es ist ein Zusammenspiel von Server und Browser.

**Comment by renma** [comment]
Accepted.
