### ISSUE TITLE
DJs using Vinyl

### ISSUE THREAD

**Issue by renma** [renma/tdjsfgs#120]
See https://tangodjsforgoodsound.info/84
I assume this DJ uses vinyl (not as specified 78RPM shellacs).

We don't have an Audio Format for this.

**Comment by autli** [comment]
Why do you think he uses vinyl?

**Comment by renma** [comment]
Possibly a wrong assumption.
The audio type is still missing.

**Comment by autli** [comment]
How about:
Playback of LPs/Shellacs
or
Analog (playback of LPs/Shellacs)

**Comment by renma** [comment]
**QUESTION**

In this context I wonder if we don't want to leave out the file extensions?

For example:
* **AIFF Audio Interchange File Format** instead of **AIFF Audio Interchange File Format (.aiff, aif)**
* **WAV Resource Interchange File Format** instead of **WAV Resource Interchange File Format (.wav)**
* **ADA Advanced Digital Audio** instead of **ADA Advanced Digital Audio (.ada)**

etc.

Shorter and more elegant, but information is lost (that everybody knows anyway?).

**Comment by autli** [comment]
I would leave it as it is. It is clearer, especially with the rare ones. (But it's OK for me if you like to change)

**Comment by renma** [comment]
Added **ANALOG Playback of LPs/Shellacs** to choices.AUDIO_FORMAT_CHOICES.
Requires database migration.

**Comment by renma** [comment]
Finally:
```
AIFF Audio Interchange File Format (.aiff, aif)
FLAC Free Lossless Audio Codec (.flac, .fla)
WAV Resource Interchange File Format (.wav)
ADA Advanced Digital Audio (.ada)
ALAC Apple Lossless Audio Codec (.m4a, .mp4)
APE Monkey's Audio (.ape, .mac)
SHN Shorten (.shn)
TTA The True Audio (.tta)
WV WavPack LOSSLESS (.wv)
ANALOG Playback of LPs/Shellacs

```

**Comment by autli** [comment]
There is no display of **ANALOG Playback of LPs/Shellacs** after saving to **Alternative audio format:**. (tested only in my DJ data)

**Comment by renma** [comment]
There is a bug somewhere. I will create an issue.
