### ISSUE TITLE
Show last changed field in Django Admin Interface

### ISSUE THREAD

**Issue by renma** [renma/tdjsfgs#121]
This may work.

Create mystite/admin.py with the following:
```
class RatingAdmin(admin.ModelAdmin):
    readonly_fields = ('last_changed',)

admin.site.register(Rating,RatingAdmin)
```

**Comment by renma** [comment]
In the end it looks like this:
```
# Create an admin class
class DJAdmin(admin.ModelAdmin):
    list_display = ("name", "number_of_milongas", "last_changed", "email", )


# Register DJ Model and DJ Admin
admin.site.register(DJ, DJAdmin)
```
@autli Geht das so für dich?

**Comment by autli** [comment]
I would prefer "hidden namesort" instead of "name". Reason: it's the same as on "DJ site" and better sortable.

**Comment by renma** [comment]
Changed to
```
class DJAdmin(admin.ModelAdmin):
    list_display = ("namesort", "number_of_milongas", "last_changed", "email", )

```

**Comment by autli** [comment]
This change doesn't show the same "Name" as on DJ Site". I don't know why.

**Comment by autli** [comment]
I would prefer "User email" instead of "email". This ist the email adress I (as admin) use to come in contact to user.

**Comment by renma** [comment]
> I would prefer "User email" instead of "email".

The change now shows `useremail`:
```
class DJAdmin(admin.ModelAdmin):
    list_display = ("namesort", "name", "number_of_milongas", "last_changed", "useremail", )
```

> This change doesn't show the same "Name" as on DJ Site". I don't know why.

The admin interface shows raw database fields. The DJ page does not do this for the DJ entry. To display the DJ on the DJ page the following is done:
1. Read entry from database field `name`.
2. Magic: If the name starts with the prefix `DJ` or `TJ` (case insensitive), the prefix is omitted  from the display.

IMHO, the "magic part" can be removed at any time without problems.

**Comment by autli** [comment]
I would not remove the "magic part" on DJ site.
Admin interface: Understand, then back to "Name", "Hidden namesort" can be removed. Sorry for the circumstances.

**Comment by renma** [comment]
Changed to:
```
class DJAdmin(admin.ModelAdmin):
    list_display = ("name", "number_of_milongas", "last_changed", "useremail", )
```
