### ISSUE TITLE
Rearrange links

### ISSUE THREAD

**Issue by renma** [renma/tdjsfgs#124]
Rearrange links

from: DJs, Project, Player+DAC, Contact, Register, Login, Knowledge
to: **DJs, Project, Player+DAC, Knowledge, Contact, Register, Login**

and

from: DJs, Project, Player+DAC, Contact, Name, Knowledge
to: **DJs, Project, Player+DAC, Knowledge, Contact, Name**

**Comment by autli** [comment]
> to: DJs, Project, Player+DAC, Knowledge, Contact, Register, Login

This is (maybe?) a good idea. (Maybe not because **Knowledge** is the outside part of TDJSFGS-Site?)

> Name

I don't understand the benefit of **Name**. Less link categories?
And I don't understand the meaning of the word **Name**. Could we use **Register/Login**?
I think it's important so see when browsing, that it's possible to register.

**Comment by renma** [comment]
"Name" is a **placeholder**.

* When I am logged in, it says "René Maurer".
* If you are logged in, it says "DJ Alberto" or "Alberto".
* If Jens-Ingo is logged in it says "Jens-Ingo Brodesser".

When someone is logged in, "Register" is not displayed.
Why should we display it in this case? It has always been like this.

**Comment by autli** [comment]
Understand now

> and
from: DJs, Project, Player+DAC, Contact, Name, Knowledge
to: DJs, Project, Player+DAC, Knowledge, Contact, Name


... ist after Login. This makes sense.

> When someone is logged in, "Register" is not displayed.
Why should we display it in this case? It has always been like this.

Of course not to display in this case. I meant while browsing as a reader (not logged in).

**Comment by renma** [comment]
> This is (maybe?) a good idea.

The "maybe-case" can actually not be implemented.

**Comment by autli** [comment]
OK
