### ISSUE TITLE
Alternative audio format not displayed (anymore)

### ISSUE THREAD

**Issue by renma** [renma/tdjsfgs#125]
The alternative audio format is not displayed after SAVE.
It is only displayed in the edit view but not in the regular view.

Affected versions: **1.5.5 (productive)** and 1.5.6 (test-server).
We can't say anything about older versions.

**Comment by renma** [comment]
Huch... this bug was already present in 1.0 from 2017-12-28 :-)

```
-    {% if dj.audiofromat2 %}
-      <td>Alternative audio format:</td><td>{{ dj.get_audiofromat2_display }}</td>

+    {% if dj.audioformat2 %}
+    <td>Alternative audio format:</td><td>{{ dj.get_audioformat2_display }}</td>
```

**Comment by autli** [comment]
And none of the 34 DJs with Alternative Audio Format complained!
