### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by renma** [renma/tdjsfgs#126]
We have already released 2 times a version that had bugs that should have been noticed during testing. Our test concept with a test script seems not to be sufficient.

Automatic unit tests would help. But they are extremely complex for a web application. Some kind of dual control principle might be more feasible.

**Comment by autli** [comment]
But the Alternative Audio Format Bug is new sice 1.5.6, no?

**Comment by renma** [comment]
Until further notice we will do nothing.
