### ISSUE TITLE
Error promt

### ISSUE THREAD

**Issue by autli** [renma/tdjsfgs#13]
Edit: Rote Umrandung bei Fehler gefällt, Rot kommt aber erst, wenn man den Fehlerhinweis angeklickt hat.

**Comment by renma** [comment]
1. Was genau machst du?
2. Wie reagiert das System?
3. Welche Reaktion erwartest du?

**Comment by autli** [comment]
1. Ich mache meine public email ungültig
2. Heute auf Mac/Safari wird Name "Email" gelb ohne Fehlerbeschreibung
3. Wie 2. aber mit Fehlerbeschreibung. Wenn möglich gleichzeitig sichtbar.

**Comment by renma** [comment]
Created a more generic issue for this subject:
https://github.com/renma/tdjsfgs/issues/14
