### ISSUE TITLE
Equipment with note

### ISSUE THREAD

**Issue by autli** [renma/tdjsfgs#133]
Some DJs do not understand that under "Equipment" only the devices/tools for live use should be listed. Instead, equipment from the home studio are also listed. This makes it difficult to understand the workflow.
A note for equipment can bring clarity, on DJ-Edit even better on DJ-Site as well.
Proposals:
a) **Equipment** (live use)
b) **Equipment** live use
c) **Equipment** for live use

**Comment by renma** [comment]
I have no preference for either a), b) or c).
And actually, I don't really find the therm "live use" appropriate.

**Comment by renma** [comment]
If I understand you correctly you mean
"Other equipment used during a Milonga"?

**Comment by autli** [comment]
No, **Equipment** in blod, the heading

**Comment by renma** [comment]
Im talking about the content not the form :-)

**Comment by autli** [comment]
c) **Equipment** for live use
This is also a good formulation for me, this is how it should be.

**Comment by renma** [comment]
Draft ready in version 1.5.8c
