### ISSUE TITLE
New Field for Music Library

### ISSUE THREAD

**Issue by autli** [renma/tdjsfgs#134]
It is becoming increasingly clear in forums that both a music library and a playback software are in DJs use. For this reason, we should create a new field.
Proposal: "Music library" in "Equipment" above field "Player".
Contents of "Music library" and "Player" may be identical.

**Comment by renma** [comment]
If it is about software and programs I would use one of the following terms:

- Music library management software
Contents of "Music library management software" and "Player" may be identical
- Music library management
Contents of "Music library management" and "Player" may be identical

**One more field supports the misconception that a DJ needs to have as many and different devices and programs around as possible to produce good sound.**

**Comment by autli** [comment]
I don't think this is the case in general but it is true that it doesn't help for better sound. The same as many other information we collect and provide - but they help DJs to organize the workflow.
"Music library management" is better, I just thought that the name is too long for the list.
**We do not need to generate this field, no problem for me. We can close the issue.**

**Comment by renma** [comment]
Maybe the term is too long, can be yes, but you wrote:

> Ich würde #133 weiter verfolgen. Korrekte Inhalte höher gewichten als perfektes Design der Seiten.

I am not against the new field. It will just remain empty for most of the DJs..Or do you think that the DJs update their data? A picture, also such an open point... would of course be uploaded by all in no time...

**Comment by autli** [comment]
My plan would be to inform all DJs with a newsletter about all additions and improvements. And ask for updating data.
Hope dies at last.

**Comment by renma** [comment]
It would look something like this... is this ok?
![draft_mlm_01](https://user-images.githubusercontent.com/35080009/164884535-11642ad8-0515-4095-a642-6dfc5b07b1c4.jpg)

**Comment by autli** [comment]
Very good! Thanks

**Comment by renma** [comment]
Ok, thanks. I will do it on productive ASAP.

**Comment by renma** [comment]
One example with and one without abbreviation (both on my 14 inch monitor):

![draft_mlm_01-short](https://user-images.githubusercontent.com/35080009/164888924-b703603e-6cfb-4e1a-9668-f88d91b4e37a.jpg)
![draft_mlm_01-long](https://user-images.githubusercontent.com/35080009/164888938-28e28b11-6acf-4d2e-8ae0-9bab9fc1631e.jpg)

**Comment by autli** [comment]
Without abbreviation looks better (but not this one with type error).

**Comment by renma** [comment]
I find it without abbreviation and without typo ;-) also better.
I do it that way and hope that it will fit on the "DJ Edit" page too.

**Comment by renma** [comment]
So far the field works.  At the moment I don't know if the entry

> Contents of "Music library management" and "Player" may be identical

is needed... and if yes **where** it could be done? Perhaps we can do without it?

**Comment by autli** [comment]
A missunderstanding, sorry. I didn't think at a note but to the behavior of the fields. No restriction.
