### ISSUE TITLE
Improve input checking and handling in DJ Edit

### ISSUE THREAD

**Issue by renma** [renma/tdjsfgs#14]
The  input checking and handling in DJ Edit is maybe too basic and should be improved in some way.

**Comment by autli** [comment]
was meinst du mit "too basic"?

**Comment by renma** [comment]
Zu einfach.

**Comment by autli** [comment]
soviel verstehe ich auch, nicht aber was daran nicht gut ist. Kannst du dich weniger basic ausdrücken ;-)

**Comment by renma** [comment]
Zu einfach meint, zu einfach :) Es ist so einfach wie möglich implementiert. Ein Teil der Prüfung überrnimmt der Browser (z.B. leere Felder), ein Teil das Programm. Das ganze wäre einheeitlicher, wenn das Programm alles machen würde.

**Comment by autli** [comment]
?? Ist mir irgendwie zu hoch. Wieso sollte es denn einheitlicher sein?

**Comment by renma** [comment]
Ein einheitlches Layout und eine einheitliche  Reaktion des Systems auf einen Fehler bei einer Eingabe finde ich sinnvoll.

**Comment by renma** [comment]
See also https://github.com/renma/tdjsfgs/issues/51.

**Comment by renma** [comment]
See https://github.com/renma/tdjsfgs/issues/64

**Comment by autli** [comment]
Ergänzung zum Fehlertext (Vorschlag):
"Please correct the wrong or enter the missing data in your input."
anstatt
"Please correct the wrong data in your input!"

**Comment by renma** [comment]
Implemented.

**Comment by autli** [comment]
Sorry, aber dieser Satz scheint mir doch etwas komisch, oder?:
"Please correct the wrong or enter the missing data in your input."
Wäre nicht besser:
"Please correct mistakes in your input or enter missing data"

**Comment by autli** [comment]
"not saved"/Error Ereignissen vorbeugen mit der Markierung der Pflichtfelder (mandatory fields)?
Ich weiss nicht was technisch möglich ist. Verbreitet ist die Feldmarkierung mit Stern*

**Comment by renma** [comment]
> Wäre nicht besser:
> "Please correct mistakes in your input or enter missing data"

Finde ich nicht gut. Ich mag es **kurz und bündig**:
"Please correct wrong or missing information".

**Comment by renma** [comment]
> Ich weiss nicht was technisch möglich ist.

Fast alles.

> Verbreitet ist die Feldmarkierung mit Stern*

Wo komt der Stern hin bei einem Key-Value Paar?
key: value

**Comment by autli** [comment]
Kann mir das so vorstellen
Model:                             * Mac
Player:                             * iTunes
Audio interface/DAC:     *

**Comment by autli** [comment]
Nein, so kann ich mir das vorstellen. (Github hat mir vorhin die Leerschläge gestohlen)
![ohne titel](https://user-images.githubusercontent.com/35627082/51071413-dd72e500-1650-11e9-9bca-c22be6a1e865.png)

**Comment by autli** [comment]
> Finde ich nicht gut. Ich mag es **kurz und bündig**:
> "Please correct wrong or missing information".

Sehr gut!

**Comment by autli** [comment]
Die Frage hatten wir zwar schon mal. Ich stelle sie trotzdem:
Den Bindestrich als Eingabe in Pflichtfelder unterbinden? (nur falls es nicht viel Arbeit generiert)

![ohne titel](https://user-images.githubusercontent.com/35627082/51071551-0bf1bf80-1653-11e9-8609-eb928f9f77ce.png)

**Comment by renma** [comment]
> so kann ich mir das vorstellen

Das sind aber Punkte und nicht Sterne?
￼

**Comment by renma** [comment]
> Den Bindestrich als Eingabe in Pflichtfelder unterbinden? (nur falls es nicht viel Arbeit generiert)

Der Arbeitsaufwand tentiert gegen 0. Und der Ertrag ebsnso. Es schliesst genau einen von hundert Milionen möglichen Fehleinträgen aus. 

![img](https://user-images.githubusercontent.com/35080009/51071901-ebc4ff00-1658-11e9-8e90-d113c8ef2769.png)

**Comment by autli** [comment]
Das ist mir schon klar. Der Unterschied zum Bindestrich besteht darin, dass unser Programm den Bindestrich auch verwendet. Im Gegensatz zu anderen Zeichen sieht es mit Bindestrich so aus wie wenn alles in Ordnung wäre. Vor allem bei anderen Pflichtfeldern als EQ & Compr..

**Comment by renma** [comment]
> mit der Markierung der Pflichtfelder (mandatory fields)?

Sind die Felder Equalizer und Compressor mandatory fields?

**Comment by autli** [comment]
> Sind die Felder Equalizer und Compressor mandatory fields?

Ich würde sie so markieren:
(*)

**Comment by autli** [comment]
Was bedeuten diese 3 Buchstaben (fav)?
![bildschirmfoto 2019-01-13 um 10 34 30](https://user-images.githubusercontent.com/35627082/51083743-28f3c480-171f-11e9-8141-512c07fb939d.png)

**Comment by autli** [comment]
"Since" sollte mit Default "-------" starten.
Grund: User muss sonst keine Auswahl vornehmen obwohl mandatory und save von "default" is möglich.
Dem DJ Peter Wenger ist dies geschehen ... hatte 150 Milongas since Anfang 2018 publiziert. Ich musste ihn darauf hinweisen.

**Comment by renma** [comment]
fav ist eine Fehler im Code.

**Comment by renma** [comment]
> "Since" sollte mit Default "-------" starten.

Ist im RC1 den ich für den Releasetest vorbereite gemacht, aber noch nicht auf dem Testserver.
