### ISSUE TITLE
More support for analog DJs

### ISSUE THREAD

**Issue by renma** [renma/tdjsfgs#146]
This request was communicated to us by Andreas Kemper.

It should be possible to specify a "turntable"  as device.

This could be achieved by renaming the field "Computer" to "**Computer/Device**"
and specifying "**turntable**" as an additional selection in the drop-down menu.

**Comment by autli** [comment]
Yes, that should be the right solution.

**Comment by renma** [comment]
Is implemented in 1.6.2

**Comment by renma** [comment]
While testing the implementation, I found that probably analog DJs do not need "Player", "Audio interface/DAC" and "Backup-player".

The DJ will have to improvise somehow:
https://www.tangodjsforgoodsound.info/129

Because these are required:
![errors-on-analog-dj-edit](https://github.com/renma/tdjsfgs/assets/35080009/658e789f-5011-4e07-8115-344c92ad06f7)

**Should alanoge DJs be able to save their data without specifying "player", "audio interface/DAC" and "backup player"?**

**Comment by renma** [comment]
The same for "Music library management":
![errors-on-analog-dj-edit-2](https://github.com/renma/tdjsfgs/assets/35080009/5f22db00-391f-4edd-9dc1-f8dbdf23f07e)

**Should we ask an analog DJ what makes sense?**

**Comment by autli** [comment]
I recommend a simple solution with an **additional** note in the info field ""Equipment for live use". New info field:

_These are probably the most important data for the site. A valuable support for new DJs getting their first gear and an inspiration for advanced DJs looking for better and proven tools.
DJs working with **turntable(s)** please write in unnecessary or inappropriate fields: "Not required for analog DJing"_

**Comment by renma** [comment]
**Additional** note added to 1.6.2
