### ISSUE TITLE
Update 2024 for Linkpage

### ISSUE THREAD

**Issue by autli** [renma/tdjsfgs#149]
We should update our link page. I already checked existing links and made a list for changes and additions.
I send it to renma for an evaluation.

**Comment by renma** [comment]
I think your suggestions are good and correct! Thank you very much!
I try to update the link page as soon as possible.
IMHO there is no need for a new release.

**Comment by renma** [comment]
Linkpage updated with **./tdjs dist prod**.

```
sending incremental file list
createlinkpage.py
tangodjsforgoodsound/version.py
tangodjsforgoodsound/templates/
tangodjsforgoodsound/templates/linkpage.html

```
PROD sever restarted with **ALL/mysite/tdjs restart prod**.
New version is 3.6.2a.

@autli: OK?

**Comment by autli** [comment]
OK
