### ISSUE TITLE
Change text on contact site

### ISSUE THREAD

**Issue by autli** [renma/tdjsfgs#19]
Text von "Minimal sound requirement" inhaltlich anpassen zur Home Seite:

We search for the best transfers of the original recordings and use good quality audio tools and software (interfaces, sound cards, DACs, sound processors) for performing them.

We don't play lossy formats (e.g. mp3, aac, youtube-downloads ...).

**Comment by renma** [comment]
Inhaltlich wird die Aussage leider nicht besser, wenn wir sie wiederholen. Solange es nämlich beim Suchen bleibt (und wir nicht finden) ändert sich am Sound gar nichts.
Nicht einverstanden.

**Comment by autli** [comment]
Auch wenn ich den Test nicht perfekt finde, verstehe ich die Aussage davon anders. Nämlich so, dass der DJ (we) sich bemüht die besten Transfers zu finden, was selbstverständlich nie immer möglich ist.
Schade hast du nicht schon bei der Hauptseite interveniert. Also müssen wir die Hauptseite auch wieder rücksetzen, oder?. Im Moment fällt mir nichts besseres ein.

**Comment by renma** [comment]
Auf der Hauptseite ist der Text informativ (und kann meiner Meinung nach genau so bleiben wie er jetzt ist). Die Besucherinnen der Seite erfahren worum es geht.
Jetzt sprechen wir über ein REQUIREMENT (eine Anforderung). Hier sollten wir etwas exakter sein, finde ich. Mich erstaunt deine Aussage, dass es genügt, wenn sich DJanes Mühe geben (mir ist das sympathisch und es erweitert "den Kreis" gewaltig).

**Comment by autli** [comment]
"We use the best available transfers ..." ist eine absolute Bedingung welche auch ich nicht erfüllen kann. Leider wurde mir dies nicht früher bewusst und darum suche ich eine passendere Formulierung. Ich kann mir gut vorstellen dass schon einige Interessenten an dieser Hürde gestoppt wurden. Sind wir uns mindestens so einig, dass die bisherige Formulierung geändert werden muss?

**Comment by renma** [comment]
Analog zu tools:

We use good quality transfers of the original recordings.

?

**Comment by autli** [comment]
Jetzt verstehe ich dich überhaupt nicht mehr. Einerseits findest du meinen vorherigen Vorschlag sympathisch, kurz darauf möchtest du nichts ändern und jetzt kommt doch ein neuer Vorschlag???

**Comment by renma** [comment]
Locker bleiben ;-)

**Comment by autli** [comment]
Nun, ich versuche dich ernst zu nehmen.
"We use good quality transfers of the original recordings." Bin einverstanden

**Comment by renma** [comment]
Accepted.

**Comment by renma** [comment]
To be changed in DJ Edit as well.

**Comment by autli** [comment]
Kleine Änderung analog formats:
(e. g. interfaces, sound cards, DACs, sound processors).

**Comment by renma** [comment]
Ok, bitte wenn es geht nur eine Änderung pro Issue.
