### ISSUE TITLE
Change title line in mission

### ISSUE THREAD

**Issue by autli** [renma/tdjsfgs#20]
New: The mission
Grund: Es soll nicht so stark auf uns alleine bezogen sein.

**Comment by renma** [comment]
Ich verstehe das so, dass sich "Our mission" nicht auf Alberto und René bezieht, sondern auf ALLE DJanes und DJs, die sich auf der Seite eingetragen haben.
In diesem Sinne ist für mich "Our mission" deutlich passender als "The mission".

**Comment by renma** [comment]
Wenn man den Text liest, der nach der Überschrift folgt ("We are two Tango-DJs located in Switzerland aiming for a good sound in milongas"), dann muss die Leserin oder der Leser davon ausgehen, dass mit "Our" Alberto und René gemeint sind.
Schade, "The mission" gefällt mir nicht.

**Comment by renma** [comment]
Accepted.

**Comment by autli** [comment]
"Our" ist für mich auch OK, wenn dir "The" nicht gefällt

**Comment by renma** [comment]
In nächsten Release (1.1.2/rc1) ist "The" drin. Kannst ja dann Mal schauen wie das aussehen und wirken tut.
