### ISSUE TITLE
Automatic registration

### ISSUE THREAD

**Issue by renma** [renma/tdjsfgs#21]
A registration where the user isn't forced to write an email to contact@tangodjsforgoodsound.info  may lower the threshold for new users.

**Comment by autli** [comment]
Gut, das könnte in der Tat sein.

**Comment by renma** [comment]
Irgendeine Idee oder ein Mockup (https://de.wikipedia.org/wiki/Mock-up) wie und wo man das einfügen könnte.

**Comment by autli** [comment]
Wird es nur noch Automatic Registration (AR) geben und Contact wird einfache Kontaktmöglichkeit?

**Comment by renma** [comment]
Wer bestimmt das?

**Comment by renma** [comment]
Ich würde sagen: nur noch automatische Registrierung und normale Kontaktmöglichkeit.

**Comment by autli** [comment]
Einverstanden. Dann Vorschlag für neue Seiteneinteilung:
Home Mission Contact Register Login Links

**Comment by renma** [comment]
Ready for testing!

**Comment by renma** [comment]
Tests on test-server passed.
