### ISSUE TITLE
Changes for contact site

### ISSUE THREAD

**Issue by autli** [renma/tdjsfgs#25]
[Contact Text 1.1.4.docx](https://github.com/renma/tdjsfgs/files/1710740/Contact.Text.1.1.4.docx)

Schriftarten und Stile wie bisher.

**Comment by autli** [comment]
Nur noch dies:
`We will never pass your email address to third parties.`
ersetzen durch
`We will never pass any of your data to third parties`
Grund: es geht ja auch um die Namen

**Comment by renma** [comment]
Accepted
