### ISSUE TITLE
Move Logout link away from menu

### ISSUE THREAD

**Issue by renma** [renma/tdjsfgs#27]
It may be better/nicer to place the Logout Link as button inside the DJ edit content.

**Comment by autli** [comment]
Einverstanden. Du meinst "button inside the DJ Name content"?

**Comment by autli** [comment]
Einverstanden

**Comment by autli** [comment]
Möchte man nicht aus jeder Seite ausloggen können? Wenn Login im Menu erwarte ich auch Logout im Menu. Skeptisch ob dies eine Verbesserung wäre.

**Comment by renma** [comment]
Optisch ist eine Verbesserung. Den Rest kannst du dann im Mockup beurteilen. Ich logge mich NIE aus (ausser beim Testen). Das wird ja automatisch gemacht, wenn man den Browser schliesst. Mir genügt das.
Schade um die vielen vielen vielen Stunden für ein totes Projekt :-(
