### ISSUE TITLE
New field "Resident DJ"

### ISSUE THREAD

**Issue by autli** [renma/tdjsfgs#29]
Neues Feld **Resident DJ** oder **Resident DJ at** nachstehend **Website**. Typ Text (oder Weblink?)
Gründe: Motivation zur Registrierung wenn DJ auch (Mit)Organisator einer Milonga. Milongas mit gutem Sound werden sichtbarer. Tänzerinnen und Tänzer finden Milongas mit gutem Sound einfacher.

**Comment by renma** [comment]
Damit fokusieren wir auf Veranstalter und nicht auf DJ?!

Und nur weil ein DJ bei https://tangodjsforgoodsound.info dabei ist, heisst das ja nicht unbedingt, dass der Ort wo der DJ "resident" ist, auch wirklich eine Anlage hat, die in der Lage ist guten Sound zu produzieren?

Und überhaupt: Zumindest in unserer Region sind Tänzerinnen und Tänzer nicht an gutem Sound interessiert(!):
- Flores (mit LS die nicht in der Lage sind irgend etwas zu produzieren) => platschvoll.
- Singe (die Milonga mit dem deutlich besten Sound in der Region) => halbleer.

**Comment by renma** [comment]
Accepted.

**Comment by autli** [comment]
> Damit fokusieren wir auf Veranstalter und nicht auf DJ?!
Fokussieren nein, wir lassen sie minimal teilhaben.
>heisst das ja nicht unbedingt, dass der Ort wo der DJ "resident" ist, auch wirklich eine Anlage hat, die in der Lage ist guten Sound zu produzieren?
Richtig, die Wahrscheinlichkeit dafür ist aber grösser und zumindest sollte das Musikmaterial OK sein.
> Zumindest in unserer Region sind Tänzerinnen und Tänzer nicht an gutem Sound interessiert(!)
Traurig ja, das heisst aber nicht, dass dies immer so bleibt (in den letzten 16 Jahren hat sich bei DJs, Milongas und Tanzenden viel verändert). Und tdjfgs soll hoffentlich weltweit Einfluss nehmen.
>Accepted
Merci

**Comment by renma** [comment]
Warum hast du den wieder geöffnet?
