### ISSUE TITLE
Add remark to Public email

### ISSUE THREAD

**Issue by autli** [renma/tdjsfgs#3]
Edit - Public email: mit Vermerk „will be invisible for SPAM machines"

**Comment by renma** [comment]
Accepted.

**Comment by renma** [comment]
"Optional email address for contacting you,"
"will be obfuscated and is therefore hard to read for spammers."

Maybe we find something shorter for the second line?

**Comment by autli** [comment]
will not be readable for SPAM machines
oder
will not be readable for spammers

**Comment by renma** [comment]
Spammer können das schon lesen, ist aber schwierig.
Neuer Versuch:
"Optional email address for contacting you,"
"obfuscated and hard to read for SPAM machines."

**Comment by autli** [comment]
Noch zwei Vorschläge:
will be obfuscated against SPAM
will be obfuscated - against SPAM
Dein letzter Versuch ist aber auch OK
