### ISSUE TITLE
Change Website to Website DJ

### ISSUE THREAD

**Issue by autli** [renma/tdjsfgs#30]
Für eine klarere Zuordnung: In Website nach Website DJ umbenennen.

**Comment by renma** [comment]
Keine Ahnung worum es geht :-(

**Comment by autli** [comment]
Sorry, war ungenau.
Betrifft das Feld Website (Url) vom DJ. In Edit und DJ Seite.

**Comment by renma** [comment]
Wieso sollten wir das tun?

Und wieso gerade für die Webseite und für nichts anders?

Das müsste ja nach dieser Logik so aussehen:

Country DJ:
Region or City DJ:
Email DJ:	-
Website DJ:
Resident DJ at:

**Comment by autli** [comment]
Genau genommen hast du recht. Aber aus meiner Erfahrung mit vielen Datenbank-Usern befürchte ich, dass leicht mal mit **Resident DJ** verwechselt wird.
Können wir aber mal so belassen, ist OK für mich.
