### ISSUE TITLE
Rename Home to DJs?

### ISSUE THREAD

**Issue by autli** [renma/tdjsfgs#32]
Home umbenennen nach **DJs** oder **Registered DJs**?

**Comment by renma** [comment]
Als Betreiber einer Seite, die kein Home hat (http://cumparsita.ch), kann ich nicht gut argumentieren, dass jede Seite ein Home braucht ;-)

DJs und Registered DJs finde ich als "Home-Ersatz" etwas holperig. Ich könnte mir vorstellen Home (ohne DJs) und Mission ein zu einem neuen Home zusammenzufassen und dann für DJs oder Registered DJs eine neue Seite mit einem neuen Menupunkt zu machen.

**Comment by autli** [comment]
Dein Vorschlag zu einem neuen Home hat Berechtigung, generiert aber viel Arbeit. Zur Zeit lieber nicht.
_We provide good sound ....._ direkt auf der DJ-Seite finde ich halt schon noch gut, weil emotional.
Home ist für mich aber wenig sagend und sogar etwas altbacken (?). Mit DJs weiss ich sofort was ich darunter finde, wenn ich mich auf tdjsfgs umschaue. Ich kann aber auch mit Home leben.

**Comment by renma** [comment]
Implemented.
