### ISSUE TITLE
Back to Login after Password Reset

### ISSUE THREAD

**Issue by autli** [renma/tdjsfgs#35]
Testpunkt 42 verstehe ich nicht: Möchtest du, dass nach einem Passwort reset automatisch neu eingeloggt werden muss?

**Comment by renma** [comment]
Weiss nicht, aber eher ja.

**Comment by autli** [comment]
Ich nein, das würde mich nerven. Zweifelt denn da jemand daran, dass ich mir das neue PW nicht merken kann? In der Not kann immer noch PW Reset Mail ausgelöst werden.
Was sind Gründe für ein Ja?

**Comment by renma** [comment]
> Was sind Gründe für ein Ja?
Zeitnahe Sicherstellung, dass das neue Passwort passt.
Ich kann gut ohne "forced-logout" leben.
