### ISSUE TITLE
New Website Menu Item for Self Registration

### ISSUE THREAD

**Issue by autli** [renma/tdjsfgs#38]
Mein Vorschlag inkl. Reihenfolge:
DJs Mission Contact Register Login Links

**Comment by renma** [comment]
Register ist in Contact integriert.
Genügt das nicht?

**Comment by autli** [comment]
Meiner Meinung nach braucht es ganz klar einen extra Menupunkt, so wie viele andere es auch machen. Auch haben wir genug Platz in der Menuzeile.
Ich hatte selbst etwas Mühe den Weg zu der Registration zu finden ;-)

**Comment by renma** [comment]
Meiner Meinung nach braucht es keinen extra Menupunkt.

**Comment by renma** [comment]
Goodbye KISS! https://de.wikipedia.org/wiki/KISS-Prinzip.
tangodjsfoorgoodsound.info goes main stream!
Accepted.
