### ISSUE TITLE
Send email to a new registered DJ

### ISSUE THREAD

**Issue by renma** [renma/tdjsfgs#39]
Maybe we can send (automatically) a Welcome Email to  a new registered DJane or DJ.

In a second step, this Email may contain some extra information about https://tangodjsforgoodsound.info.

An idea...

**Comment by autli** [comment]
Ja, gute Idee. Würde vorerst aber nur ein Welcome-Mail machen.
Extrainformation wüsste ich im Moment nicht was, mit der Zeit vielleicht schon.

**Comment by autli** [comment]
**Mein Vorschlag** Einzeln verschicken nach Registration, ich könnte das machen. Unterzeichnen auch mit deinem Namen?
Hello ... 
Welcome to tangodjsforgoodsound! 
We are glad that you joined the list for sharing your ideas and setup.
Please note that your data is not visible on the website as long as _Number of Milongas_ is set to zero.
Just send us an email if you have any questions or if you would like to give us feedback.
Best wishes
Albert & René
https://tangodjsforgoodsound.info
Albert Alt (DJ Alberto) and René Maurer (DJ René)

**Comment by autli** [comment]
**Einverstanden**: Automatisch machen sobald Zeit dazu verfügbar. Kein Stress, bis dahin manuell von mir.

**Vorschlag** (Verbesserungen willkommen):
Hello (First Name)
Welcome to tangodjsforgoodsound! 
We are glad that you have joined the list. By sharing your ideas and setup you support our aim - thank you.
Just send us an email if you have any questions. We are also happy to receive contructive feedback.
We also speak German.
Happy DJing & Best wishes
Albert & René
https://tangodjsforgoodsound.info

**Comment by renma** [comment]
Accepted.

**Comment by renma** [comment]
forgotten to close (implemented in 1.3.4).
