### ISSUE TITLE
Change text of DJ summary

### ISSUE THREAD

**Issue by autli** [renma/tdjsfgs#4]
DJ - Summary: ändern nach "Since nnnn with about nn milongas“

**Comment by renma** [comment]
Accepted.

**Comment by renma** [comment]
Im Moment ist das Summary 2 Zeilen wie folgt:

Zeile 1: Traditional Tango DJ
Zeile 2: Since yyyy with nnn milongas

Habe ich das richtig verstanden: Zeile 1 bliebt und Zeile 2 ändert?

**Comment by autli** [comment]
ja richtig, nur in der 2. Zeile "about" hinzufügen
