### ISSUE TITLE
Send email to all when a new registration was done

### ISSUE THREAD

**Issue by renma** [renma/tdjsfgs#40]
Maybe we can send an email to all registered DJ as soon as a new DJ is registered.

An idea...

**Comment by autli** [comment]
Gute Idee ... zur Zeit eher `Nice to have`.
Wenn ja, dann aber nur mit Einverständnis der User. Z. B. mit neuem Pflichtfeld in Edit: _Newsletter Yes/No._

**Comment by renma** [comment]
Ist das mit dem Newsletter aktuell oder wird das nochmals aktuell oder kann ich den Issue schliessen?

**Comment by autli** [comment]
Ich würde schliessen aber eigentlich ist es dein Vorstoss, darum entscheide du.
