### ISSUE TITLE
DJ not showed in Menu

### ISSUE THREAD

**Issue by renma** [renma/tdjsfgs#42]
Description:
1. Login
2. DJ is showed in Menu
3. Select DJs => DJ is showed in Menu =>OK
4. Select Mission => DJ is showed in Menu =>OK
5. Select Contact => DJ is not showed in Menu =>FAILURE
6. Select Links => DJ is not showed in Menu =>FAILURE
7. Select More => DJ is showed in Menu =>OK

**Comment by renma** [comment]
Accepted.
Must fix.

**Comment by autli** [comment]
Merci für den Hinweis - muss ich wohl übersehen haben beim letzten Test.
