### ISSUE TITLE
Remove the term "DJane"

### ISSUE THREAD

**Issue by renma** [renma/tdjsfgs#47]
> I will join your group as this has been a priority for me for years. 
> However pLEASE do not cal female DJ’s DJanes. That is very insulting. Maybe
> we should call DJ’s who are men Dguys or something. 
> Please let us do away with anything smacking is sexism, even though I am
> sure you never meant it that way. But being called a DJane is truly awful.
> Please delete that phrase on behalf of your female and make colleagues. 
> We all do the the same. No reason for a sexist name. 
> Thanks!

**Comment by autli** [comment]
Ich kann die Interpretation von Ilene gut verstehen und wäre dafür unseren Text entsprechend anzupassen.

**Comment by renma** [comment]
Ich bin anderer Meinung. Eine Diskussion darüber ist sinnlos.

**Comment by renma** [comment]
Accepted.
