### ISSUE TITLE
No line break in 1.3.3 DJ-Detail Remarks

### ISSUE THREAD

**Issue by autli** [renma/tdjsfgs#49]
![no line break](https://user-images.githubusercontent.com/35627082/39049579-5608b9e4-44a2-11e8-9b2a-f1dff160bb13.png)

**Comment by renma** [comment]
It is not a bug to add no line breaks.
A bug would it be in case we add line breaks.
The text is formatted by the user (including line breaks).
IMHO.

Examples:
=
![djcomment](https://user-images.githubusercontent.com/35080009/39069019-a0ecb154-44de-11e8-9809-494f313317cd.png)
=
![djcomment2](https://user-images.githubusercontent.com/35080009/39069033-aee1adaa-44de-11e8-8e1d-224b3c2f2338.png)
=

**Comment by autli** [comment]
OK
