### ISSUE TITLE
Sort oder

### ISSUE THREAD

**Issue by renma** [renma/tdjsfgs#50]
Something seams to be wrong with sort order.
Why is Jens-Ingo first, El Baqueano last and Alberto and René in between?

**Comment by renma** [comment]
Das hat nichts mit django zu tun, sondern mit demjeneigen der das programmiert hat :)
Sortierung ist wie folgt programmiert:

  1. Land.
  2. DJ Name wobei das Wort DJ ignoriert wird.

Scheint nicht zu funktionieren (deshalb ist der Issue als **bug** markiert).

**Comment by renma** [comment]
Die Sortierung wie angegeben stimmt schon.
Das Land wird halt als Abkürzung genommen für die Sortierung:

  Belgium BE
  Switzerland CH
  China CN
  Czechia CN
  Germany DE
  United Kingdom GB
  Italy IT
  Norway NO
  United States of America US

**Comment by renma** [comment]
Welches ist die beste Sortierung, solange weniger als --- sagen wir Mal --- 50 DJs eingetragen sind?

**Comment by autli** [comment]
Zur Zeit sehe ich keine bessere Variante als so wie es ist.

**Comment by renma** [comment]
Sollte man die Abkürzungen statt den vollen Namen beim Land angeben?

**Comment by renma** [comment]
z.B.
Jens-Ingo Brodesser Brussels (BE)
DJ Alberto Bern(CH)
René Maurer Biel Bienne (CH)

**Comment by autli** [comment]
Nein, höchstens voranstellen, daran habe ich eben auch gedacht. Dann würde allen klar wie die Sortierung programmiert ist.
CH Switzerland, Biel Bienne
oder
CH-Switzerland, Bern
eher Variante 1

**Comment by renma** [comment]
Voranstellen finde ich unsinnig.
Die Variante "René Maurer Biel Bienne (CH)" gefällts mir ausgezeichnet.

Solange nicht mehr als 100 DJs eingetragen sind, könnte ich die Sortierung nach 
Ländernamen im Programm machen.

**Comment by autli** [comment]
_Voranstellen finde ich unsinnig._
Mein Grund ist, dass alle Länderkürzel ganz vorne **in einer Kolonne** stehen würden.
Mir ist das Ganze nicht so wichtig, deine zwei Vorschläge sind für mich auch OK.

**Comment by renma** [comment]
Implementation magic: Remove first 3 characters from DJ Name before displaying the list if DJ Name converted to lowercase startswith "dj " or "tj ".

**Comment by renma** [comment]
Accepted

**Comment by renma** [comment]
forgotten to close (implemented in 1.3.4).
