### ISSUE TITLE
URL field handling

### ISSUE THREAD

**Issue by renma** [renma/tdjsfgs#51]
Common short URLs like
    google.com
    tangodjsforgoodsound.info
    cumparsita.ch
are not accepted by the Website field.
This may be confusing for users.

(Maybe we can implement the same mechanism as it is done for the resident DJ fields?)

**Comment by renma** [comment]
See also https://github.com/renma/tdjsfgs/issues/14.

**Comment by autli** [comment]
> This may be confusing for users.
das habe ich auch so erfahren.

**Comment by autli** [comment]
Könnte man einen Texthinweis nach dem Feld _Website_ in DJedit einfügen?
Text: "Please insert full URL-adresses initiating "http://.... or https://...."
Oder hast du eine passendere Lösung oder besseren Text?

**Comment by renma** [comment]
Im allgemeinen werden URLs als Internet- oder Webadresse bezeichnet. Der Begriff URL-Adresse existiert IMHO nicht wirklich.

**Comment by renma** [comment]
Dein Vorschlag ist nur Murks. Sorry.

Besser IMHO:
* URLs mit Schema http oder https akzeptieren.
* URL ohne Schema mit dem Schema http versehen.

NB: Schema http funktioniert auch auch für jede sauber programmierte Seite, die https verlangt (wegen automatischer Weiterleitung), z.B: http://tangodjsforgoodsound.info.

**Comment by renma** [comment]
Fixed in 1.4.0. rc5

**Comment by autli** [comment]
Super, merci!
