### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by renma** [renma/tdjsfgs#52]
Currently all logs are disabled.
This means that we are blind in case of problems happened in the past.
We should
1. enable django logging
2. replace print statements with log statements

**Comment by autli** [comment]
1. Logging wäre für die Analytik der Vorgänge sicherlich sehr hilfreich.
2. replace print statements - sind das die Email-Sendungen über Vorgänge im System?

**Comment by renma** [comment]
print statements sind Hinweismeldungen in unserem Code, die auf die Konsole ausgegeben werden aber nirgends in eine Datei geschrieben werden.

**Comment by renma** [comment]
Logging is implemented and configured via mysite/settings.py.
There is one logger for all (file and console). The django loggers are disabled.

For now basic stuff is logged:
* An entry for every visited view
* An entry for very visited DJ detail page
* An entry for login and logout

The log file is stored on the server. It is also available on the website (Menu More).

**Comment by renma** [comment]
More logging outputs added. This should do the job for now. Requires a full test (the logger is called in the directly python code).

Log levels:
* file = INFO
* console = INFO (is ERROR better?)

**Comment by autli** [comment]
`Logout admin` is not logged - is that OK?

**Comment by renma** [comment]
It depends on what OK means for you.

As already said, there is only one logger for tdjsfgs and the django default loggers are disabled. Once logged in as admin, you leave the tangodjsforgoodsound context and there is no logger anymore. 

Logout admin is not logged -  it is implemented like this.

**Comment by autli** [comment]
It's OK for me.
