### ISSUE TITLE
Long entries are not handled exemplary

### ISSUE THREAD

**Issue by renma** [renma/tdjsfgs#55]
Maybe we should improve the handling of real long entries.

See  https://tangodjsforgoodsound.info/36.

**Comment by renma** [comment]
In the Player+DAC section, long entries are cut. This isn't advantageous at all.

**Comment by autli** [comment]
Das habe ich als logisch gefunden für lange Einträge und es hat mich nicht gestört. Ich weiss aber auch nicht, was man daran ändern könnte.

**Comment by renma** [comment]
> Ich weiss aber auch nicht, was man daran ändern könnte.

Zum Beispiel mehrere Zeilen verwenden.

**Comment by autli** [comment]
Dies hat für mich keine besondere Priorität. Wer abgeschnittenen Text lesen will wird wahrscheinlich zur Detailansicht wechseln. Ich will deinen Verbesserungen aber auch nicht im Wege stehen ;-)

**Comment by renma** [comment]
Ich habe gemeint, dass du die Player+DAC  Ansicht wolltest, weil man eben **nicht** in die Detailansicht wechseln will?
