### ISSUE TITLE
Change field Sound processer in Equipment

### ISSUE THREAD

**Issue by autli** [renma/tdjsfgs#57]
1. Change "Sound processor (s)" to "Equalizer".
2. Add a new field with name "Compressor"
3. New order of the fields as follows:
Computer: Auswahl wie bisher
Model: Freitext wie bisher
Player: Freitext wie bisher
AudioInterface/DAC: Freitext wie bisher
Equalization: Auswahl wie bisher
Equalizer: Freitext (Logikfunktion anpassen)
Compression: Auswahl wie bisher
Compressor: Freitext (Logikfunktion analog Equalizer)
Other equipment: Freitext wie bisher
Remarks: Freitext wie bisher

**Comment by renma** [comment]
Ein Feld "Sound processor(s)" existiert auch in "Rescue equipment".
Was ist damit?

**Comment by autli** [comment]
Ich weiss. So belassen, weiss im Moment nichts Besseres.

**Comment by renma** [comment]
Aktuell haben 4 DJ einen Eintrag im Feld "Rescue equipment|Sound processor(s)": Polaco, Wenger, Tobler und Gregor. Bei allen ist der Eintrag identisch mit dem Feld "Equipment|Sound processor(s).
IMHO können wir das Feld "Rescue equipment|Sound processor(s)" löschen.

**Comment by renma** [comment]
Database Migration will be complicated.

The following should be done?

If Equalization is enabled and Compression is enabled:
1. the new field "Equalizer" is set to the value of the old field "Sound processor(s)".
2. the new field "Compressor" is set to the value of the old field "Sound processor(s)".

If Equalization is enabled and Compression is disabled:
1. the new field "Equalizer" is set to the value of the old field "Sound processor(s)".
2. the new field "Compressor" is set to empty.

If Equalization is disabled and Compression is enabled:
1. the new field "Equalizer" is set to empty.
2. the new field "Compressor" is set to the value of the old field "Sound processor(s)".

If Equalization is disabled and Compression is disabled:
1. the new field "Equalizer" is set to the value of the old field "Sound processor(s)".
2. the new field "Compressor" is set to the value of the old field "Sound processor(s)".

**Comment by autli** [comment]
> Database Migration will be complicated.
> The following should be done?
Ist meine oben beschriebene Methode nicht einfacher? Feld "Sound processor (s)" einfach umbenennen nach "Equalizer" und die wenigen 4 Compressoreinträge die existieren, wovon 2 du und ich sind, manuell zügeln.
Du hast gefragt, darum habe ich geantwortet. Du bist der Programmierer, du wirst deine Gründe für deine Methode haben.
