### ISSUE TITLE
New field "Song display" in Musica?

### ISSUE THREAD

**Issue by autli** [renma/tdjsfgs#58]
Bereits 4 von 17 DJs geben Song screen or Song display in Remarks an. Brauchen wir ein neues Feld für diese Sparte? Dies würde den Bemühungen dieser DJs Achtung verschaffen.

**Comment by renma** [comment]
Anforderungen:
  https://tangodjsforgoodsound.info/17
  https://tangodjsforgoodsound.info/36 in
  https://tangodjsforgoodsound.info/1
  https://tangodjsforgoodsound.info/37

Was soll das für ein Feld sein?

**Comment by autli** [comment]
Feldname: Song display oder Song/Tanda display?
Feldtyp: Freitext

**Comment by renma** [comment]
Ein Link wäre vielleicht auch ganz nett.
Zum Beispiel http://cumparsita.ch/djrene/songscreen_rene.png

**Comment by autli** [comment]
Sieht gut aus! Wenn du willst, von mir aus machen. Hoffentlich werden die Links lange gültig sein.
