### ISSUE TITLE
New field remarks to DJ personal

### ISSUE THREAD

**Issue by autli** [renma/tdjsfgs#6]
Edit/DJ - Personal: neues Textfeld „Remarks“ oder „About me“. Brauchen wir das?

**Comment by renma** [comment]
Du warst Mal der Meinung, dass du kein "I am the best" statements möchtest.
Hast du deine Meinung geändert?

**Comment by autli** [comment]
Ja, damit,auf deinen Wunsch hin mehr Emotionen möglich sind.

**Comment by renma** [comment]
Weiss nicht, ob das der richtige Weg ist..... ein Bild der DJanes+DJs würde dem IMHO mehr entsrechen. Ist es ok, wenn das nicht als MUSS drin ist für den 1.1.0 Release?

**Comment by autli** [comment]
Völlig OK es vorläufig wegzulassen
