### ISSUE TITLE
Split field AudioInterface/DAC

### ISSUE THREAD

**Issue by renma** [renma/tdjsfgs#60]
As a consequence of https://github.com/renma/tdjsfgs/issues/57 the field  AudioInterface/DAC should probably also be devided in:

AudioInterface

and 

DAC

**Comment by autli** [comment]
Ich würde keine Trennung machen. Audio Interface und DAC sind unter Umständen schwer auseinander zu halten oder beide Elemente sind in einem Gerät enthalten. Bei den bisherigen Einträgen sehe ich nur bei René M. einen Konflikt, alle anderen Einträge passen bestens. Ich denke es würde komplizierter und damit Fehleinträge geben.

**Comment by renma** [comment]
A) Also bei mir sind DAC, Equalizer und Compressor ÜBERHAUPT NICHT auseinander zu halten. Es ist nähmlich ein und dasselbe Gerät (ergibt 3 Felder mit demselben EIntrag).

B) Bei Equalizer und Compressor war ja das gerade  das Argument:  mehr Felder = weniger Fehleinträge. Hier ist es jetzt umgekehrt: mehr Felder = mehr Fehleinträge.

**Comment by autli** [comment]
Deine Argumente A und B sind richtig. Trotzdem, wo siehst du bei den bisherigen DJ-Einträgen einen Falscheintrag?

**Comment by renma** [comment]
Mir geht es um eine korrekte Implementierung der Seite. Wie wir gesehen haben, sind Fehleinträge sowieso immer möglich.
