### ISSUE TITLE
Change field name AudioInterface/DAC?

### ISSUE THREAD

**Issue by autli** [renma/tdjsfgs#61]
Wäre **Audio Interface & DAC** die passendere Bezeichnung als **AudioInterface/DAC**? Ich finde ja.

**Comment by renma** [comment]
Nein.

**Comment by renma** [comment]
Besser wäre vielleicht DAC?

**Comment by renma** [comment]
Was um Gottes Willen soll in diesem Feld eigentlich eingetragen werden?

**Comment by autli** [comment]
> Besser wäre vielleicht DAC?

Nein. Einige DJs oder die Hersteller werden die Geräte als Audio Interface verstehen.
Bsp.: https://focusrite.com/de/scarlett

**Comment by autli** [comment]
> Was um Gottes Willen soll in diesem Feld eigentlich eingetragen werden?

??? Die Geräte welche unsere DJs zu sozusagen 100% richtig eingetragen haben.
Bevor sich die Haare auszuraufen, würde ich belassen wie es ist ;-)
