### ISSUE TITLE
When Equalization and Compression is 'never'

### ISSUE THREAD

**Issue by autli** [renma/tdjsfgs#62]
sollen dann die Felder Equalizer und Compressor gesperrt sein? Oder ist offen besser? Aktuell bleiben die Felder offen.

**Comment by renma** [comment]
Mit offen meinst du editerbar?

Ich finde offen besser. Ich kann einen Equalizer oder Compressor haben und trotzdem 'never' eintragen, weil ich die vielleicht wirklich eher 'never' als 'sometimes' nutze.

Vielleicht braucht es eine zusätzliche Wahlmöglichkeit "very rarely" oder so...

**Comment by autli** [comment]
> Ich finde offen besser.
Ich eigentlich auch ... im Zweifel für den Angeklagten.
> Vielleicht braucht es eine zusätzliche Wahlmöglichkeit "very rarely" oder so...
Eher nein, man könnte ja auch unter Remarks schreiben.
