### ISSUE TITLE
Edit: Info "Wrong Data" highlighted yellow

### ISSUE THREAD

**Issue by autli** [renma/tdjsfgs#63]
Für eine schnellere Erkennung des Problems wenn 'Save' misslingt:
**Wrong Data** gelb markieren in der Infozeile "Please correct the **Wrong Data** in your input!"
Gründe: Weil der Browser in der Liste nach oben springt kann das fehlerhafte Feld nicht mehr im sichtbaren Bereich liegen und muss zuerst gefunden werden.
Die Infozeile "Please correct the **Wrong Data** in your input!" unterscheidet sich optisch wenig von der Umgebung.

Könnte als Alternative der Browser nach Save mit Fehler auch einfach nur zum fehlerhaft gelb angezeigtem Feld springen?

**Comment by renma** [comment]
Es wäre schon gut, wenn der Browser nach Save mit Fehler einfach zum gelb angezeigtem Feld springen würde. Das braucht IMHO jacvascript und das haben wir (noch) nicht.

Gelb Markierung geht.
Nur **Wrong Data** oder die ganze Zeile?

**Comment by autli** [comment]
> Gelb Markierung geht.
> Nur Wrong Data oder die ganze Zeile?
Weiss nicht was besser ist. Entscheide du.

**Comment by renma** [comment]
Implementiert mit Hintergrundfarbe für Text = #ff6 (gelb).
