### ISSUE TITLE
Edit: Wrong highlighted field in rare cases

### ISSUE THREAD

**Issue by autli** [renma/tdjsfgs#64]
Wenn ein gelb markiertes Feld korrigiert wird und gleichzeitig (ohne Save zwischendurch) ein Plichtfeld auf default (------) gesetzt wird, verschwindet die Gelbmarkierung auf dem korrigierten Feld nicht. Beispielsequenz:
1. Equalization: Always und Equalizer: (leer) --> Gelbmarkierung von Equalizer
2. Equalizer mit Text versehen und gleichzeitig Style auf (------) stellen
3. Save --> Gelbmarkierung auf Equalizer bleibt

**Comment by renma** [comment]
IMHO ist das Verhalten korrekt.
Equalization = "--------" ist eine **ungültige** Eingabe, der Benutzer **muss** etwas selektieren.

Chromium (V69.0.3497.100) weist den Benutzer darauf hin, dass etwas eingeben werden muss (siehe Screenshot). Ich hatte das auch mit dem Safari von Béatrice und mit IE getestet und da hat das auch funktioniert .

NB: Die Tests müssen natürlich schon mit Mac/Safari und Win/IE durchgeführt werden. 

![save_eq_without_selection](https://user-images.githubusercontent.com/35080009/46336232-83628c80-c62a-11e8-8092-d8a74f48f11c.png)

**Comment by renma** [comment]
Aktuell ist das unser Konzept: nähmlich, dass Felder soweit möglich vom Browser validiert werden. Das führt in deinem Beispiel dazu, dass beim Drücken von SAVE nichts zum Server übertrageben wird (weil der Browser einen Fehler festgestellt hat) und deshalb bleibt das Feld Equalization gelb.

Siehe  https://github.com/renma/tdjsfgs/issues/14

**Comment by autli** [comment]
Inzwischen habe ich noch Bild von meiner Situation geschossen. Das kann den User halt schon sehr verwirren wenn seine Aufmerksamkeit beim Gelb hängen bleibt.
OK, danke für die Erklärung, jetzt verstehe ich. Dann lassen wir das so, oder?
![img_4618](https://user-images.githubusercontent.com/35627082/46338702-2b7b5400-c631-11e8-9078-bec17199c449.jpg)

**Comment by renma** [comment]
Ist eine Konzeptänderung. Möglichkeiten:

a) Tests abbrechen. Änderung definieren und implementieren. Tests neu starten.

b) So lassen und weiter testen (https://github.com/renma/tdjsfgs/issues/64 und https://github.com/renma/tdjsfgs/issues/14 bleiben offen).

**Comment by autli** [comment]
Ich bin vorläufig für Variante b).
Gründe: Grosser Aufwand, wenig Zeit, wenige User und der beschriebene Bug ergibt sich IMHO in seltenen Situationen.

**Comment by renma** [comment]
Also b).

NB: Dieses Verhalten ist schon lange und immer wieder in der Kritik, scheint also schon relevant zu sein.
