### ISSUE TITLE
New view: Player and audiointerface overview 

### ISSUE THREAD

**Issue by renma** [renma/tdjsfgs#65]
[tdjfgs_player_and_audiointerface_v1.pdf](https://github.com/renma/tdjsfgs/files/2647362/tdjfgs_player_and_audiointerface_v1.pdf)

**Comment by renma** [comment]
Name of table = Technology.
Place of table = Between Mission and Contact.

**Comment by autli** [comment]
> Name of table = Technology.
Proposal: Tech overview

**Comment by renma** [comment]
Ugly.
Tech overview implemented in
* Menu
* Technology

**Comment by autli** [comment]
> Ugly.
Dann **nicht** machen! Deine Meinung ist immer auch gefragt. Es war nur ein Vorschlag!
Vorschlag2: Technologies

**Comment by renma** [comment]
Schon gemacht :)
Technique?

**Comment by renma** [comment]
Techniques implemented in Menu and Technology.

**Comment by renma** [comment]
Könnte man den Englischlehrer fragen, was die beste Bezeichnung ist?

**Comment by autli** [comment]
Lieber nicht, wir haben keinen Kontakt mehr zum Lehrer. Ich frage mal B..

**Comment by autli** [comment]
Brainstorming for Menu (my favorites so far):
- Players+DACs
- Players&DACs
- Techniques

**Comment by renma** [comment]
Ist falsch in RC3  Player+DAC statt Players+DACs.

**Comment by autli** [comment]
Falsch? Nicht aus meiner Sicht. Im Entscheid-Email an dich habe ich bewusst 2x Player+DAC in Einzahl geschrieben weil ich es ästhetischer finde und weil ich es jetzt als Rubrik der Tabelle verstehe. DAC kann man so auch als Überbegriff für Digital-Analog-Conversion und nicht als Gerätebezeichnung verstehen. So kann das Interface auch etwas Platz haben ohne genannt zu werden..
Wenn dir aber die Mehrzahl besser gefällt, ist dies für mich auch OK.

**Comment by renma** [comment]
Sorry, oben im Brainstorming steht
* Players+DACs
* Players & DACs
* Techniques

**Comment by autli** [comment]
Ja, ich weiss schon. Das war aber vor meinem erneuten Brainstorming vom 11. Dez. und meinem Mail an dich vom 12. Dez.:
_"Ich äussere mich nicht zum Namen der "Technology" Seite, ich warte auf deinen Entscheid.
Hmm…?
Dann: "Player+DAC overview" oder "Player+DAC" oder “Technology". Wähle einfach ohne dich zu äussern ;-)"_
**Mein Fehler**, dass ich versäumt habe diese Info auch unserem Github mitzuteilen. **Player+DAC** ist also weiterhin meine Präferenz aus weiter oben geschilderten Gründen. Wenn du lieber die Version in Mehrzahl hast geht dies auch für mich.

**Comment by renma** [comment]
Ja, ich habe leider das entsprechende Email vergessen oder nicht mehr Blickfeld (kann bei  +50'000 archivierten Emails schon Mal vorkommen ;.)

Ich schaue eigentlich nur auf GitHub, wenn ich am Programmieren bin. https://github.com/renma/tdjsfgs/issues (mit dem Filter "is:issue is:open") ist meine Referenz was es zu tun gibt.

Alles andere geht leider ab un dzu vergessen. Sorry.

Implementiert ist "Player+DAC" ohne Leerzeichen.
