### ISSUE TITLE
New field "updated"?

### ISSUE THREAD

**Issue by autli** [renma/tdjsfgs#67]
Sollten wir die letzte Aktualisierung der DJ-Einträge publik machen mit einem Feld "updated"?
Ich meine ja um die Aktualität der Daten einschätzen zu können.
Ort: "DJ Detail" ganz unten, oder etwa Seite "Technology"?

**Comment by renma** [comment]
Macht IMHO auf der Seite Technology keinen Sinn.
Wenn schon dann in DJ Detail.

**Comment by renma** [comment]
Draft online.
Ist das so gemeint.

**Comment by autli** [comment]
Finde ich gut.

**Comment by renma** [comment]
Ich hebe bei bei mir eine Änderung gemacht. Nun ist bei mir - und nur bei mir - der 8. Dezember drin, als "Last changed".
