### ISSUE TITLE
Delete function for 'DJ' in List Techniques

### ISSUE THREAD

**Issue by autli** [renma/tdjsfgs#68]
Sinngemäss Liste `Registered DJs`.

**Comment by renma** [comment]
Entschuldigung, ich verstehe nicht, was du willst.
* Es gibt **eine** Datenbank (mit 2 Tabellen) die verschieden dargestellt wird (Ansicht "Djs" und Ansicht "Techniques"). Es gibt **keine** Listen. Das kannst du gut sehen, wenn du dich als *admin* einloggen tust.
* DJs können sich nur selber löschen, wenn sie denn  eingleoggt sind. Dann verschwinden sie auch aus "Techniques".
* Falls ein gelöschter DJ in "Techniques" oder ein DJ mit Anzahl Milongas = 0 immer noch in "Techniques" auftaucht, dann ist das ein Fehler in der Programmierung.

**Comment by autli** [comment]
Sorry, **remove** wäre wohl besser gewesen als **delete**. Es geht nur um den DJ Titel vor dem Namen.
![dj titel weg](https://user-images.githubusercontent.com/35627082/49686011-5204b200-faee-11e8-8dca-e31ba66f2d0a.png)

**Comment by renma** [comment]
Aha der Murks ;-)
Ok fixed.
