### ISSUE TITLE
Register: Details for a correct password?

### ISSUE THREAD

**Issue by autli** [renma/tdjsfgs#70]
Es wäre hilfreich die Mindestanzahl für das Passwort anzugeben. Ansonsten könnte DJ eventuell verärgert sein bei vielen Fehlversuchen (?).

**Comment by renma** [comment]
Einverstanden.
Wie genau sollte der Text lauten und wo genau sollte er platziert sein?

Aktuelle register form:

![register](https://user-images.githubusercontent.com/35080009/49931087-610cab00-fec6-11e8-9d64-c8a817165230.png)

Aktuelle change password form:

![changepw](https://user-images.githubusercontent.com/35080009/49931086-610cab00-fec6-11e8-8b97-acb5bd3bbcda.png)

**Comment by autli** [comment]
Text (3x identisch):
Sorry, your password input is not valid.
Possible errors: too short (must be at least 8 characters), too simple, no match between passwords.

Orte (3x in Error message):
Wie bisher vorhanden in Register, Login-PW Reset-New password, DJ edit-Change password

**Comment by renma** [comment]
Fixed in 1.4.0 rc3.

**Comment by autli** [comment]
Entweder stimmt meine obige Angabe "(must contain characters and numbers) nicht oder die Prüfung Passwort "too simple" funktioniert nicht entsprechend. Aktuell kann ein PW aus 8 characters gültig sein.

**Comment by renma** [comment]
Ich weiss nicht **woher** du deine obige Angabe hast.
IMHO muss ein Passwort mindestens 8 Zeichen lang sein und darf nicht nur aus Zahlen bestehen.

**Comment by autli** [comment]
Woher? Hatte ich irgendwie (falsch) im Hinterkopf. Ist im Programm die Definition für ein gültiges PW nicht einsehbar?
Was jetzt? Error message ändern nach: 
Sorry, your password input is not valid.
Possible errors: too short (must be at least 8 characters), too simple (numbers only is not allowed), no match between passwords.

**Comment by renma** [comment]
Natürlich ist das im Programm einsehbar. Und wir haben:

* 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator
which checks the similarity between the password and a set of attributes of the user.
* 'django.contrib.auth.password_validation.MinimumLengthValidator'
which simply checks whether the password meets a minimum length.
* 'django.contrib.auth.password_validation.CommonPasswordValidator'
which checks whether the password occurs in a list of common passwords. By default, it compares to an included list of 1000 common passwords.
* 'django.contrib.auth.password_validation.NumericPasswordValidator'
which checks whether the password isn’t entirely numeric.

**Comment by renma** [comment]
Fixed: too simple (numbers only is not allowed).
