### ISSUE TITLE
DJ edit: Bestehende Mailadresse nur bedingt erkannt

### ISSUE THREAD

**Issue by autli** [renma/tdjsfgs#73]
Wird eine bestehende Emailadresse mit einem Grossbuchstaben eingegeben wird sie nicht als bereits bestehend erkannt und ist funktionell.
Gilt für Public Email sowie leider auch Login Email

**Comment by renma** [comment]
Fixed in 1.4.2

**Comment by autli** [comment]
Tested und für gut befunden.
