### ISSUE TITLE
Register: Error message not highlighted

### ISSUE THREAD

**Issue by autli** [renma/tdjsfgs#74]
Es wäre gut für die rasche Erkennung des Problems, wenn schon hier gelb markiert würde bei Fehler.
Betrifft:
"Sorry, your password input is not valid. 
Possible errors: too short (must be at least 8 characters), too simple (numbers only is not allowed), no match between passwords."

**Comment by renma** [comment]
Implemented

**Comment by autli** [comment]
ich habe bei meinen fehlerhaften Registrierversuchen **nie** gelb gesehen. Geht es bei dir?

**Comment by renma** [comment]
Moved to #78
