### ISSUE TITLE
Mandatory fields should be marked in DJ edit

### ISSUE THREAD

**Issue by renma** [renma/tdjsfgs#76]
See #14.
Mandatory fields should be marked in DJ edit.
Fields which are mandatory if another field has  a certain value should be marked different.

**Example mandatory field:**
<code>Style: * Traditional and alternative</code>

**Example semi-mandatory field:**
<code>Equalizer: (*) API 5500 Dual Equalizer</code>

**Comment by renma** [comment]
Implemented 1.4.4

**Comment by autli** [comment]
1.4.4
"Region or City" ist nicht markiert als mandatory
"Alternative audio format" ist nicht mandatory aber als solches markiert.
"RESQUE: Audio interface/DAC" ist nicht mandatory aber als solches markiert.

![bildschirmfoto 2019-01-13 um 11 13 22](https://user-images.githubusercontent.com/35627082/51084063-44150300-1724-11e9-8ba1-aba59bce3acd.png)

![bildschirmfoto 2019-01-13 um 11 14 15](https://user-images.githubusercontent.com/35627082/51084067-660e8580-1724-11e9-8f2d-9bd1e07e0ed3.png)
![bildschirmfoto 2019-01-13 um 11 15 21](https://user-images.githubusercontent.com/35627082/51084075-89d1cb80-1724-11e9-9e7a-27525b86b5cb.png)

**Comment by autli** [comment]
Klammern in rc1 immer noch falsch
![51084160-9acf0c80-1725-11e9-8229-77b452e0ef9f](https://user-images.githubusercontent.com/35627082/51104901-bbf83180-17e7-11e9-975d-bf1fccc5ca37.png)

**Comment by renma** [comment]
Fixed in 1.4.4 rc2
