### ISSUE TITLE
Mark all error message yellow

### ISSUE THREAD

**Issue by renma** [renma/tdjsfgs#78]
Maybe we should mark all error messages yellow.
Not yellow so far:
1. Login: error message on wrong password input not yellow
2. Password reset: Sorry, the system cannot find the email address specified.
3. Register: Sorry, this isn't one of the ‚big four‘ orchestras.
4. Contact: Sorry, this isn't one of the ‚big four‘ orchestras.
5. Contact: Sorry, this isn't a valid email address.

**Comment by renma** [comment]
Updated in 1.4.5:

1. ~~Login: error message on wrong password input not yellow.~~
2. ~~Password reset: Sorry, the system cannot find the email address specified.~~
3. Register: Sorry, this isn't one of the ‚big four‘ orchestras.
4. ~~Contact: Sorry, this isn't one of the ‚big four‘ orchestras.~~
5. ~~Contact: Sorry, this isn't a valid email address.~~
6. ~~Change password: Sorry, your password input is not valid.~~

**Comment by renma** [comment]
3. also updated in 1.4.5:

3. ~~Register: Sorry, this isn't one of the ‚big four‘ orchestras.~~

**Comment by renma** [comment]
@autli 
Kannst du den Issue bitte schliessen, falls für dich ok oder bitte sagen, was noch nicht stimmt.

**Comment by autli** [comment]
getestet und für gut befunden.
