### ISSUE TITLE
Version string not always on bottom of screen

### ISSUE THREAD

**Issue by renma** [renma/tdjsfgs#80]

**Comment by renma** [comment]
Das ist komplizierter als gedacht... ich bin einfach kein [CSS](https://www.w3schools.com/html/html) Spezialist. Ich habe die Version Mal nach unten rechts (und immer sichtbar) verschoben. Wäre das was?

**Comment by autli** [comment]
Mit diesen Farben?
![bildschirmfoto 2019-01-30 um 16 38 51](https://user-images.githubusercontent.com/35627082/51992668-b409e400-24ad-11e9-9e51-3be126dc0a5c.png)

**Comment by renma** [comment]
Farben wie immer. Das ist die Entwicklerversion, damit ich sehe welche Bereiche der Seite wo sind.

**Comment by autli** [comment]
Das sehe ich zum ersten Mal so farbig, zum Glück ;-)
IMHO ist es weniger gut, wenn die Version-Nr. in den Textinhalt läuft als dass diese Angabe nicht jederzeit sichtbar ist. Wer diese Angabe sucht wird sie finden, den Anderen wird es wahrscheinlich egal sein.

**Comment by renma** [comment]
> Das sehe ich zum ersten Mal so farbig, zum Glück ;-)

Ich finde den blauen Hintergrund echt cool.

**Comment by renma** [comment]
Footer removed in 1.4.5.
Version information moved to mission in 1.4.5.
