### ISSUE TITLE
Contact: No longer use browser validation

### ISSUE THREAD

**Issue by renma** [renma/tdjsfgs#81]
The contact form still uses Browser based validation.

**Comment by renma** [comment]
Implemented in 1.4.5 without browser validation.

@autli
Ich mag die Sterne nicht so recht. Was meinst du?

**Comment by autli** [comment]
Wo soll ich schauen? http://tangodjsforgoodsound.cumparsita.ch
-> Service Temporarily Unavailable (am Morgen sowie auch jetzt).

**Comment by renma** [comment]
> Service Temporarily Unavailable (am Morgen sowie auch jetzt).

Das ist normal. Auf dem cumparsita server läuft tangodjsforgoodsound.info nur als Ausnahme, wie zum Beispiel jetzt.

**Comment by autli** [comment]
Gut so, merci.
