### ISSUE TITLE
Test Issue

### ISSUE THREAD

**Issue by renma** [renma/tdjsfgs#83]
Testen ob Albi ein Email bekommt :)

**Comment by autli** [comment]
So bekomme ich Mail, merci für den Test. Ich meine, dass bisher immer nur die Eröffnung eines Issue nicht gekommen ist. Sobald ich mich daran beteiligt habe, hat's funktioniert.
Meine Einstellungen waren immer wie folgt:

![bildschirmfoto 2019-01-17 um 10 18 01](https://user-images.githubusercontent.com/35627082/51308155-c57cd600-1a41-11e9-8b90-32cda6812325.png)

**Comment by autli** [comment]
Das habe ich jetzt auch aktiviert. Ich sollte wohl besser English verstehen.
Ich nehme an, dass es jetzt auch ohne Assignee klappt, oder ...

**Comment by renma** [comment]
Vielleicht. Ich habe #84 ohne Assignees gemacht.

**Comment by autli** [comment]
Ist subito angekommen.
