### ISSUE TITLE
Test Issue 2

### ISSUE THREAD

**Issue by renma** [renma/tdjsfgs#84]
Schauen ob autli ein email bekommt ohne Assignee.

**Comment by autli** [comment]
Komisch, ich habe wieder keine Mails erhalten zu den Stern-Issues. Habe keine Einstellungen geändert inzwischen!? Und SPAM ist leer.

**Comment by renma** [comment]
Watch gesetzt?

![img](https://user-images.githubusercontent.com/35080009/51410444-f86bba80-1b64-11e9-90a0-596568dcee9c.png)

**Comment by autli** [comment]
war bei mir auf Not watching .... jetzt Watching. Aber wieso hat es zwischendurch funktioniert?
Egal, wahrscheinlich bin ich jetzt einen kleinen Schritt weiter Github bedienen zu können.
