### ISSUE TITLE
Replace star for required fields

### ISSUE THREAD

**Issue by renma** [renma/tdjsfgs#88]
The star is not ideal for marking a required field as it is not centered vertically:

Example: ---*---

**Comment by renma** [comment]
We can use loast: &lowast;
Done in 1.4.5

**Comment by autli** [comment]
Very good. Gefällt mir, merci.

**Comment by renma** [comment]
Heisst das, dass ich #81, #86, #87 und #88 gelegentlich schliessen kann?
