### ISSUE TITLE
Password change test case missed in test instructions

### ISSUE THREAD

**Issue by renma** [renma/tdjsfgs#92]
There is no test case for a successful password change in DJ Edit. Test cases 18 and 19 are about wrong user inputs while  test cases 6-11 are for password reset and case 56 is for register.

**Comment by autli** [comment]
Stimmt. Ich erinnere mich aber, den erfolgreichen Passwortwechsel geprüft zu haben.
Machst du den Testpunkteintrag oder hast du dies offline schon gemacht oder soll ich?

**Comment by renma** [comment]
> oder soll ich?

Gern.

**Comment by autli** [comment]
erledigt.
