### ISSUE TITLE
Menu entry "DJ name" wrong (when logged in)

### ISSUE THREAD

**Issue by renma** [renma/tdjsfgs#94]
Error is only present when a user/DJ is logged in.

After login the correct name (DJ name of the logged in user) is displayed in the Menu. When  another DJ is selected from the list of DJs (via the "DJs" Menu or the "Player+DAC" Menu) the selected DJ is now showed in the menu.

This is wrong, the menu should always show the DJ name of the logged in user.

**Comment by autli** [comment]
Correct. An important discovery, thanks.

**Comment by renma** [comment]
Fixed in 1.5.2
