### ISSUE TITLE
Improvement of the link page

### ISSUE THREAD

**Issue by renma** [renma/tdjsfgs#96]
These new links would really help the site:
* Jens-Ingo http://tango-dj.be
* Theresa Faus http://www.theresa-tango.de
* Hlynur Helgason http://artinfo.is/tango
* CT http://www.argentango.ch
* Frank Jin https://barriodetango.co.uk
* El Espejero http://elespejero.wordpress.com
* Clive Harrison https://barriodetango.co.uk

**Comment by renma** [comment]
We should only adjust linkpage.csv.
Can you do this Alberto? With a normal text editor like TextEdit, Sublime, Atom or Emacs (beside others).
You can get the csv-file from here https://cumparsita.ch/linkpage.zip

**Comment by autli** [comment]
I can try, I already have created a new list a few days ago.

**Comment by autli** [comment]
How about renaming the link page from: **Links** to **Knowledge**
This could be more attractive.

**Comment by renma** [comment]
Ready for testing

**Comment by autli** [comment]
Knowledge page tested - it's OK. Thanks.

**Comment by renma** [comment]
URL unchanged https://tangodjsforgoodsound.info/linkpage.
For me /linkpage is not so bad :-)

**Comment by autli** [comment]
Rename comment of **tango-dj.at** from "Onlineshop" to "Database and onlineshop".
Rearrange to postion two after **tango.info**.

**Comment by renma** [comment]
Changed in version 1.5.7.
